<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>MinimalGrpcTemplate.Client</AssemblyName>
        <RootNamespace>MinimalGrpcTemplate.Client</RootNamespace>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishAot>true</PublishAot>
        <InvariantGlobalization>true</InvariantGlobalization>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="..\Protos\V1\Common\connectivity.proto">
            <ProtoRoot>..\Protos</ProtoRoot>
            <Link>Protos\V1\connectivity.proto</Link>
            <GrpcServices>Client</GrpcServices>
        </Protobuf>
        <Protobuf Include="..\Protos\V1\Server\server.proto">
            <ProtoRoot>..\Protos</ProtoRoot>
            <Link>Protos\V1\server.proto</Link>
            <GrpcServices>Client</GrpcServices>
        </Protobuf>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Google.Protobuf" Version="3.27.3" />
      <PackageReference Include="Grpc.Net.Client" Version="2.65.0" />
      <PackageReference Include="Grpc.Tools" Version="2.65.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

</Project>
